routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', function () {
    return view('auth/login');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home/Finanzas/{id}', 'GastosController@show')->name('detallefinanza');
Route::get('/eliminar/{id}', 'GastosController@destroyGasto')->name('eliminarGastos');
Route::post('/editar/{id}', 'GastosController@update')->name('jajaja');
Route::get('/lista/{id}', 'GastosController@lista')->name('lista');
Route::get('/download/{file}', 'GastosController@archivo')->name('archivo');
// Router actas

Route::get('/s1o1l1i1c1i1t1u1d1e1s', 'ActasController@lista')->name('solicitudes');
Route::get('/i1n1f1o/{id}', 'ActasController@info')->name('informacion');

Route::get('/actasGeneradas', 'actasGeneradasController@lista')->name('aGeneradas');

Route::get('/actasD/{id}', 'ActasController@pdf')->name('pdf');
Route::get('/downloadActa/{file}', 'ActasController@archivo')->name('archivoActa');
Route::post('/EnviarActa', 'ActasController@actualizar')->name('actualizar');
Route::resource('/home/solicitudes', 'ActasController');

Route::resource('/home/actas', 'actasGeneradasController');
Route::resource('/home/Finanzas', 'GastosController');

//ACTIVIDADES victor

Route::get('/home/actividades', 'ActividadesController@index')->name('actividades');
Route::get('/home/actividades/{id}', 'ActividadesController@show')->name('informacionActividades');

Route::get('/actividades/{id}', 'ActividadesController@lista')->name('listaActividades');
Route::get('/eliminarA/{id}', 'ActividadesController@destroyActividad')->name('eliminarActividades');
Route::put('/editarA/{id}', 'ActividadesController@update')->name('editarActividades');

Route::post('/actividades/', 'ActividadesController@store')->name('crearActividad');

//ASOCIACIONES PATO

Route::get('/home/Asociaciones', 'AsociacionesController@index1')->name('asociaciones');
Route::get('/home/Asociaciones/{id}', 'AsociacionesController@show')->name('integrantesasociacion');
Route::get('/listaAsociaciones', 'AsociacionesController@index')->name('listaasociaciones');
Route::get('/Home/Asociaciones/miembrosAsociaciones/{id}', 'AsociacionesController@miembros')->name('miembrosasociaciones');
Route::get('/Home/vercuentas', 'AsociacionesController@cuentas')->name('vercuentas');
Route::get('/Home/vercuentas/{id}', 'AsociacionesController@eliminarCuenta')->name('eliminarCuenta');
Route::put('/editar1/{id}', 'AsociacionesController@update')->name('asociacionesupdate');
Route::post('/Home/Asociaciones', 'AsociacionesController@store')->name('agregarasociacion');
Route::post('/peliminar', 'AsociacionesController@eliminar')->name('eliminarasociacion');
// Denuncias victor

Route::get('/home/denuncias', 'DenunciasController@index')->name('denuncias');
Route::get('/home/denuncias/{id}', 'DenunciasController@show')->name('informacionDenuncias');
Route::get('/denuncias/{id}', 'DenunciasController@lista')->name('listaDenuncias');
Route::post('/Denuncias/', 'DenunciasController@store')->name('crearDenuncia');

Route::get('/eliminard/{id}', 'DenunciasController@destroyDenuncias')->name('eliminarDenuncia');
Route::put('/editard/{id}', 'DenunciasController@update')->name('editarDenuncia');

Route::get('Home/infoFinanciera', 'ActividadesController@verGastos')->name('verGastos');
Route::get('/asociaciones', 'ActividadesController@listarAsociaciones')->name('listarAsociaciones');
Route::get('/AsociacionesF/{id}/{fecha}', 'ActividadesController@AsociacionesF')->name('AsociacionesF');

resources/views/dde/DetallesGastos.blade.php
@extends('layouts.dde')
@section('meta')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection
@section('content')
<h2 class="panel-body text-center" style="color:#333390">Rendir gastos </h2>
<div class="gastos">
    
    <div class="tabla-gastos" id="{{ $id }}" url="{{ env('APP_URL') }}:8000/lista/">
    </div>
    
    <div class="loader" ></div>
    <!-- modal ingresar -->
    <div id="modalingresar" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content " style="filter:alpha(opacity=50); opacity:0.9;">
                <div class="container">
                    <form id="formIngresar" action="{{ route('Finanzas.store') }}" method="POST">
                        {{ csrf_field() }}                              <br>
                        <h4 style="text-align: center; color: #3F78BF">Insertar datos</h4>
                        <br/>
                        
                        <label>Descripción:</label>
                        <input type="text" required="" name="descripcion" placeholder="Descripcion"  id="descripcion" class="form-control"/>
                        <label>Dinero utilizado:</label>
                        <input type="number" required="" placeholder="Monto utilizado" name="montoUtilizado" id="montoUtilizado" class="form-control" />
                        <label>Detalle de boleta:</label>
                        <input type="text" required="" placeholder="Detalle boleta" name="detalleBoleta" id="detalleBoleta" class="form-control" />
                        <label>Fecha:</label>
                        <input type="date" required="" placeholder="Fecha del gasto" min="2017-01-01" name="fecha" id="fecha" class="form-control" />
                        
                        <label>archivo:</label>
                        <input type="file" required="" name="archivo" id="archivo" class="form-control" onchange="return fileValidation()" />
                        <label>Nombre empresa:</label>
                        <input type="text" required="" name="nombreE" placeholder="Nombre Empresa"  id="nombreE" class="form-control"/>
                        <label>Rut empresa:</label>
                        <input type="text" name="rutE" id="rutE" placeholder="rut Empresa" class="form-control" onchange="validaRut(this)" required="">
                        <input type="hidden" id="idA" value="{{ $id }}" name="idA" />
                        <input id="signup-token" name="_token" type="hidden" value="{{csrf_token()}}" />
                        
                        <br/>
                        <button   class="btn btn-info form-control ingresar" id="ingresar"> Ingresar</button>
                        <br>
                        
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
    <!-- modal editar -->
    <div id="modaleditar" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content " style="filter:alpha(opacity=50); opacity:0.9;">
                <div class="container">
                    <form id="FEditar" action="  " method="POST">
                         {{ csrf_field() }} 
                        <br>
                        <h4 style="text-align: center; color: #3F78BF">Actualizar datos</h4>
                        <br>
                        
                        <label>Descripción:</label>
                        <input type="text" required="" name="descripcionU"  id="descripcionU" class="form-control">
                        <label>Dinero utilizado:</label>
                        <input type="number" required="" name="montoUtilizadoU" id="montoUtilizadoU" class="form-control" >
                        <label>Detalle de boleta:</label>
                        <input type="text" required="" name="detalleBoletaU" id="detalleBoletaU" class="form-control" >
                        <label>Fecha:</label>
                        <input type="date" required="" name="fechaU" id="fechaU" class="form-control">
                        
                        <label>archivo:</label>
                        <input type="file" name="archivoE" id="archivoE" class="form-control" onchange="return archivo()" />
                        <label>Nombre empresa:</label>
                        <input type="text" required="" name="nombreEE" placeholder="Nombre Empresa"  id="nombreEE" class="form-control"/>
                        <label>Rut empresa:</label>
                        <input type="text" name="rutEE" id="rutEE" placeholder="rut Empresa" class="form-control" onchange="validaRut(this)" required="">
                        
                        <input type="hidden" id="idA" value="{{ $id }}" name="idA">
                        <input id="signup-token" name="_token" type="hidden" value="{{csrf_token()}}">
                        
                        <br>
                        <input type="submit" value="Editar" href="" class="btn btn-info form-control btnEditar"> </input>
                        <br>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script type="text/javascript" src="{{ asset('js/gastos.js') }}"></script>
@endsection

resources/views/dde/actividades.blade.php
@extends('layouts.dde')

@section('content')
<div class="actividades">
                        
                        @isset ($asociaciones)
                            <h2 class="panel-body text-center" style="color:#333390">Mis agrupaciones </h2>
                        @endisset
                        
                        <br>
                        @isset ($asociaciones)
                            <table class="table table-inverse">
                            <thead>
                                <tr>
                                    <th class="text-center">Nombre</th>
                                    <th class="text-center">Descripcion</th>
                                    <th class="text-center">Detalles</th>

                                </tr>
                            </thead>
                            <tbody>
                                
                                    @foreach ($asociaciones as $element)
                                    <tr>
                                             <th class="text-center" class="text-center">{{ $element->nombre }}</th>
                                             <th class="text-center">{{ $element->descripcion }}</th>
                                             <th class="text-center">
                                                
                                                <form action="{{ route('informacionActividades',$element->id) }}" type="POST">
                                                    <input class="btn btn-info" type="submit" value="Ver detalle">
                                                </form>
                                             </th>
                                    </tr>
                                    @endforeach
                                
                            </tbody>
                        </table>
                        @endisset
</div>


                       
                                         
                       
                        
                       
      

@endsection

resources/views/dde/dde.blade.php
@extends('layouts.dde')

@section('content')

    
            

                        <h2 class="panel-body text-center">Bienvenido {{auth::user()->name}}</h2>
                        <p class="text-center">Has logeado como {{ auth::user()->rol }}</p>
                    
             
            
        
    

@endsection

resources/views/dde/detalleActividad.blade.php
@extends('layouts.dde')
@section('content')
<h2 class="panel-body text-center" style="color:#333390">Actividades</h2>

<div class="actividades">
    <div  class="tablaA"  id="{{$id}}" url="{{ env('APP_URL') }}">
        
    </div>
</div>
<!-- modal ingresar -->
<div id="modalingresar" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content " style="filter:alpha(opacity=50); opacity:0.9;">
            <div class="container">
                <form id="formIngresar" action="{{ route('crearActividad') }}" method="POST">
                    <h4 style="text-align: center; color: #3F78BF">Insertar datos</h4>
                    <br>
                    <div id="alerta1" class="alert alert-warning" role="alert"></div>
                    <label>Nombre:</label>
                    <input type="text" required="" name="nombreA"  id="nombreA" class="form-control">
                    <label>Objetivo:</label>
                    <input type="text" required="" name="objetivoA" id="objetivoA" class="form-control" >
                    <label>Fecha:</label>
                    <input type="date" required="" name="fechaA" min="2019-07-24" id="fechaA" class="form-control" >
                    <label>Hora:</label>
                    <input type="time" required="" name="horaA" id="horaA" class="form-control">
                    <label>Lugar:</label>
                    <input type="text" required="" name="lugarA" id="lugarA" class="form-control">
                    <label>Descripcion:</label>
                    <input type="text" required="" name="descripcionA" id="descripcionA" class="form-control">
                    
                    <input type="hidden" id="idA" value="{{ $id }}" name="idA">
                    <input id="signup-token" name="_token" type="hidden" value="{{csrf_token()}}">
                    
                    <br>
                    <a  class="btn btn-info form-control ingresar" id="ingresar"> ingresar</a>
                    <br>
                    
                </form>
                
            </div>
        </div>
    </div>
</div>
<!-- modal editar -->
<div id="modaleditar" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content " style="filter:alpha(opacity=50); opacity:0.9;">
            <div class="container">
                <form action="  " method="POST">
                    <br>
                    <h4 style="text-align: center; color: #3F78BF">Actualizar datos</h4>
                    <br>
                    
                    <div id="alerta2" class="alert alert-warning" role="alert"></div>
                    <label>Nombre:</label>
                    <input type="text" required="" name="nombreAE"  id="nombreAE" class="form-control">
                    <label>Objetivo:</label>
                    <input type="text" required="" name="objetivoAE" id="objetivoAE" class="form-control" >
                    <label>Fecha:</label>
                    <input type="date" required="" name="fechaAE" id="fechaAE" class="form-control" >
                    <label>Hora:</label>
                    <input type="text" required="" name="horaAE" id="horaAE" class="form-control">
                    <label>Lugar:</label>
                    <input type="text" required="" name="lugarAE" id="lugarAE" class="form-control">
                    <label>Descripcion:</label>
                    <input type="text" required="" name="descripcionAE" id="descripcionAE" class="form-control">
                    
                    
                    
                    <input type="hidden" id="idA" value="{{ $id }}" name="idA">
                    <input id="signup-token" name="_token" type="hidden" value="{{csrf_token()}}">
                    
                    <br>
                    <a href="" class="btn btn-info form-control btnEditar"> Editar</a>
                    <br>
                    
                </form>
                
            </div>
        </div>
    </div>
</div>

</div>



@endsection
@section('script')
<script type="text/javascript" src="{{ asset('js/actividades.js') }}"></script>
@endsection

resources/views/dde/finanza.blade.php
@extends('layouts.dde')

@section('content')
<div class="finanza">
                        @isset ($Gastos)
                            <h2 class="panel-body text-center" style="color:#333390">Rendir gastos </h2>
                        @endisset
                        @isset ($asociaciones)
                            <h2 class="panel-body text-center" style="color:#333390">Mis agrupaciones </h2>
                        @endisset
                        
                        <br>
                        @isset ($asociaciones)
                            <table class="table table-inverse">
                            <thead>
                                <tr>
                                    <th class="text-center">Nombre</th>
                                    <th class="text-center">Descripcion</th>
                                    <th class="text-center">Detalles</th>

                                </tr>
                            </thead>
                            <tbody>
                                
                                    @foreach ($asociaciones as $element)
                                    <tr>
                                             <th class="text-center" class="text-center">{{ $element->nombre }}</th>
                                             <th class="text-center">{{ $element->descripcion }}</th>
                                             <th class="text-center">
                                                
                                                <form action="{{ route('detallefinanza',$element->id) }}" type="POST">
                                                    <input class="btn btn-info" type="submit" value="Ver detalle">
                                                </form>
                                             </th>
                                    </tr>
                                    @endforeach
                                
                            </tbody>
                        </table>
                        @endisset
</div>

<div class="gastos">
                           @isset ($Gastos)
                            
                            <table class="table table-inverse">
                                <thead>
                                    <tr>
                                        <th class="text-center">Descripcion</th>
                                        <th class="text-center">Monto Utlizado</th>
                                        <th class="text-center">Detalle boleta</th>
                                        <th class="text-center">Archivo</th>

                                       <th class="text-center"><a href=""><i class="fas fa-plus"></i></a></th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($Gastos as $element)
                                    <tr>
                                        <th class="text-center" class="text-center">{{ $element->descripcion }}</th>
                                        <th class="text-center">{{ $element->montoUtilizado}}</th>
                                        <th class="text-center" class="text-center">{{ $element->detalleBoleta }}</th>
                                        <th class="text-center">{{ $element->archivo}}</th>
                                         <th class="text-center"><a href="{{  route('detallefinanza', $element->id)  }}"> <i class="fas fa-trash-alt"></i></a>
                                        <a href="{{  route('detallefinanza', $element->id)  }}"><i class="fas fa-align-justify"></a></th>
                                    </tr>
                                    @endforeach
                                    
                                </tbody>
                            </table>
                        @endisset  
</div>
                       
                            
                       
                        
                       
      

@endsection
@section('script')
<script type="text/javascript" src="{{ asset('js/finanza.js') }}"></script>
@endsection

resources/views/dde/gestionAsociacion.blade.php
@extends('layouts.dde')
@section('meta')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection





<script>
  function sololetras(e){
  key=e.keyCode || e.which;
  teclado=String.fromCharCode(key).toLowerCase();
  letras="abcdefghijklmnñopqrstuvwxyz";
  especiales="8-37-38-46-164";
  teclado_especial=false;
  for(var i in especiales){
  if(key==especiales[i]){
  teclado_especial=true;break;
    }
    }
    if(letras.indexOf(teclado)==-1 && !teclado_especial){
    return false;

  }
  }
</script>


@section('content')
<div class="ver asociaciones">
  
  
  <h2 class="panel-body text-center" style="color:#333390">Asociaciones</h2>
  
  
  <br>
  <div id="alerta" class="alert alert-success" role="alert"></div>
  <div url="{{ route('eliminarasociacion') }}" id="tabla" class="tabla"></div>


  
  
</div>

<!-- Modal Editar -->
<div id="modaleditar" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="titulo">Editar Asociación</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id='formeditar' url="{{env('APP_URL')}}" >
          {{ csrf_field() }}
          <div id="alerta2" class="alert alert-warning" role="alert"></div>
          <label>Nombre:</label>
          <input type="text" name="nombre"  id="nombre1" class="form-control" onkeypress="return sololetras(event)">
          <br>
          <label>Descripción:</label>
          <input type="text" name="descripcion" id="descripcion1" class="form-control"">
          <br>
          <label>Detalles:</label>
          <input type="text" name="detalles" id="detalles1" class="form-control" onkeypress="return sololetras(event)">
          <input id="signup-token" name="_token" type="hidden" value="{{csrf_token()}}">
        </form>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button id="btnedit" class="btn btn-primary">Editar</button>
      </div>
    </div>
  </div>
</div>

<!-- modal ingresar -->




<div id="modalingresar" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content " style="filter:alpha(opacity=50); opacity:0.9;">
      <div class="container">
        <form id="formIngresar" action="{{ route('agregarasociacion') }}" method="POST">
          <br>
          <h4 style="text-align: center; color: #3F78BF">Insertar datos</h4>
          <br>
          <div id="alerta1" class="alert alert-warning" role="alert"></div>
          <label>Nombre:</label>
          <input type="text" required="" name="nombre"  id="nombre2" class="form-control">
          <label>Descripción:</label>
          <input type="" required="" name="descripcion" id="descripcion2" class="form-control" >
          <label>Correo:</label>
          <input type="email" required="" name="correo" id="correo2" class="form-control" placeholder="usuario@gmail.com" >
          <label>Objetivo:</label>
          <input type="text" required="" name="objetivo" id="objetivo2" class="form-control">
          <br>



          <label>Directiva</label><hr>
          
 <label for="sel1">Presidente:</label>
      <select class="form-control" id="presi">
        <option value="Elegir">Elegir</option>
        @foreach ($email as $element)
          <option value="{{$element->id}}">{{$element->email}}</option>
        @endforeach
      </select>
  <br>
<br>
               
  <label for="sel1">Tesorero:</label>
    
       <select class="form-control" id="teso">
        <option value="Elegir">Elegir</option>
        @foreach ($email as $element)
          <option value="{{$element->id}}">{{$element->email}}</option>
        @endforeach
      </select>
   
  <br>

         <br> 
            
  <label for="sel1">Secretario:</label>
     
         <select class="form-control" id="secre">
          <option value="Elegir">Elegir</option>
        @foreach ($email as $element)
          <option value="{{$element->id}}">{{$element->email}}</option>
        @endforeach
      </select>
      
  <br>
<br>
          
          
          <input type="hidden" id="idA" value="" name="idA">
          <input id="signup-token" name="_token" type="hidden" value="{{csrf_token()}}">
          
          <br>
          <a  class="btn btn-info form-control ingresar" id="ingresar"> Ingresar</a>
          <br>
          <br>
          
        </form>
        
      </div>
    </div>
  </div>
</div>
@endsection
@section('script')
<script type="text/javascript" src="{{ asset('js/asociaciones.js') }}"></script>
@endsection

resources/views/dde/indexActas.blade.php
@extends('layouts.dde')
@section('meta')
<meta content="{{ csrf_token() }}" name="csrf-token">
@endsection
@section('content')
<div class="actas">
	<h2 class="panel-body text-center" style="color:#333390">
	Solicitudes de asociaciones
	</h2>
	<br>
	</br>
	<div class="loader" ></div>
	<div id="tablaSolicitudes" url="{{ env('APP_URL') }}">
		
	</div>
	<div id="modaleditar" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content " style="filter:alpha(opacity=50); opacity:0.9;">
				<div class="container">
					<div id="info"></div>
					
				</div>
			</div>
		</div>
	</div>
	<div id="modalFormulario" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content " style="filter:alpha(opacity=50); opacity:0.9;">
				<div class="container">
					<form id="formularioActa" action="{{ route('solicitudes.store') }}">
						{{ csrf_field() }}  
						<br><br>
						<h4 class="text-center">Formulario envio acta</h4>
						<label>Descripcion:</label>
						<input type="text" class="form-control" id="descripcion" placeholder="Descripcion" 	name="descripcion">
						<label>Comentario:</label>
						<input type="text" class="form-control" id="comentario" placeholder="Comentario" 	name="comentario">
						<label>Archivo:</label>
						<input type="file" class="form-control" id="archivo" onchange="return fileValidation()"	name="archivo">
						<input id="signup-token" name="_token" type="hidden" value="{{csrf_token()}}" />
						<br>
						<button type="button" id="btnEA" class="btn btn-outline-success form-control">Enviar</button>
					</form>
					
				</div>
			</div>
		</div>
	</div>
	
</div>
@endsection
@section('script')
<script type="text/javascript" src="{{ asset('js/actas.js') }}"></script>
@endsection

resources/views/dde/indexF.blade.php
@extends('layouts.dde')
@section('meta')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection
@section('content')
<div id="tablaF" url="{{ env('APP_URL') }}">
</div>
<!-- modal ingresar -->
<div id="modalVer" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content " style="filter:alpha(opacity=50); opacity:0.9;">
            <div class="container">
            <form id="formIngresar" action="" method="POST">
                {{ csrf_field() }}
                <br>
                <h4 style="text-align: center; color: #3F78BF">Insertar datos</h4>
                <br/>
                
                    <label>Fecha</label>
                    
                    
                    
                    <div class="row">
                    <select name="select" id="fecha" class="form-control col-6">
                        
                        <option value="2018">2018</option>
                        <option value="2019" selected>2019</option>
                        <option value="2020" >2020</option>
                        <option value="2021">2021</option>
                        <option value="2022" >2022</option>
                    </select>
                    
                    
                    
                    <br/>
                    <button   class="btn btn-info form-control ingresar offset-1 col-5" id="ingresar"> Buscar  <i class="fas fa-search"></i></button>
                    <br>
                    </div>
                
                <br><br>
                <hr>
                <div id="datos">
                    <table class="table table-inverse">
                        <thead>
                            <tr>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Descripcion</th>
                                
                                
                            </tr>
                        </thead>
                        <tbody>
                            
                            
                        </tbody>
                    </table>
                    
                </div>
                <br><br><br>
            </form>
            </div>
        </div>
    </div>
</div>
</div>
<!-- modal editar -->
@endsection
@section('script')
<script type="text/javascript" src="{{ asset('js/InforFinanciera.js') }}"></script>
@endsection

resources/views/dde/integrantesasociacion.blade.php
@extends('layouts.dde')
@section('meta')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection
@section('content')
<h2 class="text-center" style="color: #110F63">Miembros de la agrupación</h2>
<br><br>
<table class="table table-hover">
	<thead>
		<tr>
			<th class="text-center">Nombre</th>
			<th class="text-center">Email</th>
			<th class="text-center">Cargo</th>
			
			
		</tr>
	</thead>
	<tbody>
		
		@foreach ($Miembros as $element)
		<tr>
			<th class="text-center" class="text-center">{{ $element->name }}</th>
			<th class="text-center">{{ $element->email }}</th>
			<th class="text-center">{{ $element->nombre }}</th>
			
			
		</tr>
		@endforeach
		
	</tbody>
</table>

@endsection
@section('script')
<script type="text/javascript" src="{{ asset('js/gestionasociacion.js') }}"></script>
@endsection