routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', function () {
    return view('auth/login');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home/Finanzas/{id}', 'GastosController@show')->name('detallefinanza');
Route::get('/eliminar/{id}', 'GastosController@destroyGasto')->name('eliminarGastos');
Route::post('/editar/{id}', 'GastosController@update')->name('jajaja');
Route::get('/lista/{id}', 'GastosController@lista')->name('lista');
Route::get('/download/{file}', 'GastosController@archivo')->name('archivo');
// Router actas

Route::get('/s1o1l1i1c1i1t1u1d1e1s', 'ActasController@lista')->name('solicitudes');
Route::get('/i1n1f1o/{id}', 'ActasController@info')->name('informacion');

Route::get('/actasGeneradas', 'actasGeneradasController@lista')->name('aGeneradas');

Route::get('/actasD/{id}', 'ActasController@pdf')->name('pdf');
Route::get('/downloadActa/{file}', 'ActasController@archivo')->name('archivoActa');
Route::post('/EnviarActa', 'ActasController@actualizar')->name('actualizar');
Route::resource('/home/solicitudes', 'ActasController');

Route::resource('/home/actas', 'actasGeneradasController');
Route::resource('/home/Finanzas', 'GastosController');

//ACTIVIDADES victor

Route::get('/home/actividades', 'ActividadesController@index')->name('actividades');
Route::get('/home/actividades/{id}', 'ActividadesController@show')->name('informacionActividades');

Route::get('/actividades/{id}', 'ActividadesController@lista')->name('listaActividades');
Route::get('/eliminarA/{id}', 'ActividadesController@destroyActividad')->name('eliminarActividades');
Route::put('/editarA/{id}', 'ActividadesController@update')->name('editarActividades');

Route::post('/actividades/', 'ActividadesController@store')->name('crearActividad');

//ASOCIACIONES PATO

Route::get('/home/Asociaciones', 'AsociacionesController@index1')->name('asociaciones');
Route::get('/home/Asociaciones/{id}', 'AsociacionesController@show')->name('integrantesasociacion');
Route::get('/listaAsociaciones', 'AsociacionesController@index')->name('listaasociaciones');
Route::get('/Home/Asociaciones/miembrosAsociaciones/{id}', 'AsociacionesController@miembros')->name('miembrosasociaciones');
Route::get('/Home/vercuentas', 'AsociacionesController@cuentas')->name('vercuentas');
Route::get('/Home/vercuentas/{id}', 'AsociacionesController@eliminarCuenta')->name('eliminarCuenta');
Route::put('/editar1/{id}', 'AsociacionesController@update')->name('asociacionesupdate');
Route::post('/Home/Asociaciones', 'AsociacionesController@store')->name('agregarasociacion');
Route::post('/peliminar', 'AsociacionesController@eliminar')->name('eliminarasociacion');
// Denuncias victor

Route::get('/home/denuncias', 'DenunciasController@index')->name('denuncias');
Route::get('/home/denuncias/{id}', 'DenunciasController@show')->name('informacionDenuncias');
Route::get('/denuncias/{id}', 'DenunciasController@lista')->name('listaDenuncias');
Route::post('/Denuncias/', 'DenunciasController@store')->name('crearDenuncia');

Route::get('/eliminard/{id}', 'DenunciasController@destroyDenuncias')->name('eliminarDenuncia');
Route::put('/editard/{id}', 'DenunciasController@update')->name('editarDenuncia');

Route::get('Home/infoFinanciera', 'ActividadesController@verGastos')->name('verGastos');
Route::get('/asociaciones', 'ActividadesController@listarAsociaciones')->name('listarAsociaciones');
Route::get('/AsociacionesF/{id}/{fecha}', 'ActividadesController@AsociacionesF')->name('AsociacionesF');

resources/views/layouts/admin.blade.php
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" id="bootstrap-css" rel="stylesheet">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js">
</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
</script>
<!------ Include the above in your HEAD tag ---------->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta content="IE=edge" http-equiv="X-UA-Compatible">
        <meta content="width=device-width, initial-scale=1" name="viewport">
        <meta content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3" name="description">
        @yield('meta')
        <title>
        {{ config('app.name', 'Laravel') }}
        </title>
        <link href="//ubiobio.cl/favicon.ico" rel="shortcut icon" type="image/x-icon">
        <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
        <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
        <link href="{{ asset('css/sidebar.css') }}" rel="stylesheet" type="text/css">
        <script src="{{ asset('js/sidebar.js') }}" type="text/javascript">
        </script>
        <link href="{{ asset('toast/toastr.min.css')}}" rel="stylesheet" type="text/css">
    </link>
    <style type="text/css">
        .loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: url('{{ asset('img/loading.gif') }}') 50% 50% no-repeat rgb(249,249,249);
    opacity: .6;
}
    </style>
</link>
</link>
</link>
</link>
</meta>
</meta>
</meta>
</meta>
</head>
<body>
<div class="page-wrapper chiller-theme toggled">
<a class="btn btn-sm btn-dark" href="#" id="show-sidebar">
<i class="fas fa-bars">
</i>
</a>
<nav class="sidebar-wrapper" id="sidebar">
<div class="sidebar-content">
<div class="sidebar-brand">
    <input class="align-middle" disabled="" src="{{ asset('img/logoubb.png')}}" style="margin-right: 10px;" type="image" width="25">
    <a href="{{  route('home') }} ">
        {{ config('app.name', 'Laravel') }}
    </a>
    <div id="close-sidebar">
        <i class="fas fa-times">
        </i>
    </div>
    </input>
</div>
<div class="sidebar-header">
    <div class="user-info">
        <span class="user-name">
            {{ Auth::user()->name }}
        </span>
        <span class="user-role">
            {{Auth::user()->rol}}
        </span>
        <span class="user-status">
            <i class="fa fa-circle">
            </i>
            <span>
                Online
            </span>
        </span>
    </div>
</div>
<!-- sidebar-search  -->
<div class="sidebar-menu">
    <ul>
        <li class="header-menu">
            <span>
                General
            </span>
        </li>
        <li class="sidebar-dropdown">
            <a href="#">
                <i class="fa fa-user-circle">
                </i>
                <span>
                    Mi asociaciones
                </span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                   
                    <li>
                        <a href="{{ route('actividades') }}">
                            Actividades
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('Finanzas.index') }}">
                            Info financiera
                        </a>
                    </li>
                   
                </ul>
            </div>
        </li>
        <li class="sidebar-dropdown">
            <a href="#">
                <i class="fa fa-exclamation-triangle">
                </i>
                <span>
                    Denuncias
                </span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="{{ route('denuncias') }}">
                            Ver denuncias
                        </a>
                    </li>
                   
                </ul>
            </div>
        </li>
        <li class="sidebar-dropdown">
            <a href="#">
                <i class="fa fa-users">
                </i>
                <span>
                    Asociaciones
                </span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="{{ route('asociaciones') }}">
                            Ver asociaciones
                        </a>
                    </li>
                    
                </ul>
            </div>
        </li>
        <li class="sidebar-dropdown">
            <a href="#">
                <i class="fa fa-exclamation-circle">
                </i>
                <span>
                    Solicitudes
                </span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="{{ route('solicitudes.index') }}">
                            Ver solucitud
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="sidebar-dropdown">
            <a href="#">
                <i class="far fa-money-bill-alt">
                </i>
                <span>
                    Informacion financiera
                </span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="{{ route('verGastos') }}">
                            Ver informacion
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="sidebar-dropdown">
            <a href="#">
                <i class="fa fa-book">
                </i>
                <span>
                    Actas
                </span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    
                    <li>
                        <a href="{{ route('actas.index') }}">
                            Ver actas
                        </a>
                    </li>
                    
                </ul>
            </div>
        </li>
        <li class="sidebar-dropdown">
            <a href="#">
                <i class="fab fa-github-alt">
                </i>
                <span>
                    Cuentas
                </span>
            </a>
            <div class="sidebar-submenu">
                <ul>
                    <li>
                        <a href="{{ route('vercuentas') }}">
                            Ver cuentas
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('register') }}">
                            Agregar cuentas
                        </a>
                    </li>
                    
                </ul>
            </div>
        </li>
    </ul>
</div>
<!-- sidebar-menu  -->
</div>
<!-- sidebar-content  -->
<div class="sidebar-footer">
<a href="#">
    <i class="fa fa-bell">
    </i>
</a>
<a href="#">
    <i class="fa fa-envelope">
    </i>
</a>
<a href="#">
    <i class="fa fa-cog">
    </i>
</a>
<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
    <span class="badge-sonar">
    </span>
    <i class="fa fa-power-off">
    </i>
</a>
<form action="{{ route('logout') }}" id="logout-form" method="POST" style="display: none;">
    {{ csrf_field() }}
</form>
</div>
</nav>
<!-- sidebar-wrapper  -->
<main class="page-content">
<div class="container-fuild">
<div class="container-fluid" style="background: white;width: 100%;  height: 100%">
    @yield('content')
</div>
</div>
</main>
</div>
</body>
</html>
</link>
<!-- page-content" -->
<!-- page-wrapper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js">
</script>
<script src="{{ asset('toast/toastr.min.js') }}" type="text/javascript">
</script>
<script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js">
</script>
<script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js">
</script>

@yield('script')

resources/views/layouts/dde.blade.php
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="shortcut icon" href="//ubiobio.cl/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/sidebar.css') }}">
    <script type="text/javascript" src="{{ asset('js/sidebar.js') }}"></script>
    <link href="{{ asset('toast/toastr.min.css')}}" rel="stylesheet" type="text/css">
 <style type="text/css">
        .loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: url('{{ asset('img/loading.gif') }}') 50% 50% no-repeat rgb(249,249,249);
    opacity: .6;
}
    </style>

</head>

<body>
<div class="page-wrapper chiller-theme toggled">
  <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
         <input type="image" src="{{ asset('img/logoubb.png')}}" width="25"  class="align-middle" disabled="" style="margin-right: 10px;">
        <a href="{{  route('home') }}">{{ config('app.name', 'Laravel') }}</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <div class="sidebar-header">
        
        <div class="user-info">
          <span class="user-name"> {{ Auth::user()->name }} 
          </span>
          <span class="user-role">{{Auth::user()->rol}}</span>
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
        </div>
      </div>
     
      
      <!-- sidebar-search  -->
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span>General</span>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-user-circle"></i>
              <span>Mi asociaciones</span>
              
            </a>
            <div class="sidebar-submenu">
              <ul>
                
                <li>
                  <a href="{{ route('actividades') }}">Actividades</a>
                </li>
                <li>
                  <a href="{{ route('Finanzas.index') }}">Info financiera</a>
                </li>
                
              </ul>
            </div>
          </li>
          
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-users"></i>
              <span>Asociaciones</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{{ route('asociaciones') }}">Ver asociaciones</a>
                </li>
                
              </ul>
            </div>
          </li>
        <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-exclamation-circle"></i>
              <span>Solicitudes</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{{ route('solicitudes.index') }}">Ver solucitud</a>
                </li>            
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
           <i class="far fa-money-bill-alt"></i>
              <span>Informacion financiera</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{{ route('verGastos') }}">Ver informacion</a>
                </li>
              </ul>
            </div>
          </li>
          
        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
      <a href="#">
        <i class="fa fa-bell"></i>
        
      </a>
      <a href="#">
        <i class="fa fa-envelope"></i>
        
      </a>
      <a href="#">
        <i class="fa fa-cog"></i>
        
      </a>
      <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
        <span class="badge-sonar"></span>
        <i class="fa fa-power-off"></i>
      </a>
      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          {{ csrf_field() }}
      </form>

    </div>
  </nav>
  <!-- sidebar-wrapper  -->
  <main class="page-content">
    <div class="container-fuild">
       <div class="container-fluid" style="background: white;  height: 100%">
   @yield('content')
    </div>
</div>
    </div>
  </main>
  <!-- page-content" -->
</div>
<!-- page-wrapper -->
   <!-- page-wrapper -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js">
</script>
<script src="{{ asset('toast/toastr.min.js') }}" type="text/javascript">
</script>
<script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js">
</script>
<script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js">
</script>
@yield('script')
</body>

</html>

resources/views/layouts/estudiantes.blade.php
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="shortcut icon" href="//ubiobio.cl/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/sidebar.css') }}">
    <script type="text/javascript" src="{{ asset('js/sidebar.js') }}"></script>
  <link href="{{ asset('toast/toastr.min.css')}}" rel="stylesheet" type="text/css">
<style type="text/css">
        .loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: url('{{ asset('img/loading.gif') }}') 50% 50% no-repeat rgb(249,249,249);
    opacity: .6;
}
    </style>
</head>

<body>
<div class="page-wrapper chiller-theme toggled">
  <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
         <input type="image" src="{{ asset('img/logoubb.png')}}" width="25"  class="align-middle" disabled="" style="margin-right: 10px;">
        <a href="{{  route('home') }}">{{ config('app.name', 'Laravel') }}</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <div class="sidebar-header">
        
        <div class="user-info">
          <span class="user-name"> {{ Auth::user()->name }} 
          </span>
          <span class="user-role">{{Auth::user()->rol}}</span>
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
        </div>
      </div>
     
      
      <!-- sidebar-search  -->
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span>General</span>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-user-circle"></i>
              <span>Mi asociaciones</span>
              
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{{ route('actividades') }}">Actividades</a>
                </li>
                <li>
                  <a href="{{ route('Finanzas.index') }}">Info financiera</a>
                </li>
                
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-exclamation-triangle"></i>
              <span>Denuncias</span>
             
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{{ route('denuncias') }}">
                    Ver denuncias 
                  </a>
                </li>
                
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-users"></i>
              <span>Asociaciones</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="{{ route('asociaciones') }}">Ver asociaciones</a>
                </li>
               
              </ul>
            </div>
          </li>
          
          
        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
      <a href="#">
        <i class="fa fa-bell"></i>
        
      </a>
      <a href="#">
        <i class="fa fa-envelope"></i>
        
      </a>
      <a href="#">
        <i class="fa fa-cog"></i>
        
      </a>
      <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
        <span class="badge-sonar"></span>
        <i class="fa fa-power-off"></i>
      </a>
      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>

    </div>
  </nav>
  <!-- sidebar-wrapper  -->
  <main class="page-content">
    <div class="container-fuild">
       <div class="container-fluid" style="background: white;  height: 100%">
   @yield('content')
    </div>
</div>
    </div>
  </main>
  <!-- page-content" -->
</div>
<!-- page-wrapper -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js">
</script>
<script src="{{ asset('toast/toastr.min.js') }}" type="text/javascript">
</script>
<script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js">
</script>
<script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js">
</script>
@yield('script')
</body>

</html>